library(cmdstanr)
iter=4000
options(mc.cores = parallel::detectCores() -1)
set_cmdstan_path(path = "/work/ext-unil-ctgg/tdaniel/genomicarchitecture/cmdstan")
sm <- cmdstan_model("/work/ext-unil-ctgg/tdaniel/genomicarchitecture/models/simple.stan")
#sm <- stan_model("simple.stan")
#height_simple<- sm$sample(ukb_data,chains=2,iter_warmup =ceiling(iter/2), iter_sampling = ceiling(iter/2),thin=1, threads_per_chain = 10, refresh=10)
logger::log_info('optimizing')
ukb_list <- readRDS('../data/data_mean_ukb_height.rds') 
#height_simple<- sm$sample(ukb_list,chains=2,iter_warmup =ceiling(iter/2), iter_sampling = ceiling(iter/2),thin=1, threads_per_chain = 10, refresh=10)
height_simple<- sm$optimize(data=ukb_list)
logger::log_info('summarising')
height_simple$summary(c("sigma","S_coef"))
logger::log_info('saving')
height_simple$save_output_files()
#saveRDS(height_simple, "height_simple.rds")
